# Generated by Django 4.2.7 on 2023-11-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smakosz', '0002_alter_profile_phone_number_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='how_many',
            field=models.CharField(max_length=2),
        ),
    ]
