# Generated by Django 4.2.7 on 2023-12-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smakosz', '0003_alter_reservation_how_many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
