# Generated by Django 4.2.7 on 2023-12-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smakosz', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
